version: '3.8'

services:
  boxbounty:
    build: .
    ports:
      - "5000:5000"
    environment:
      - TRACKING_API_KEY=YOUR-17TRACK-API-HERE
    restart: unless-stopped
    volumes:
      - ./app.py:/app/app.py
      - ./templates:/app/templates
      - ./static:/app/static
